"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client import utils
from nws_api_client.types import BaseModel
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated


class TimeoutErrorTData(BaseModel):
    additional_properties: Annotated[
        Optional[Dict[str, Any]], pydantic.Field(exclude=True)
    ] = None

    message: Optional[str] = None


class TimeoutErrorT(Exception):
    r"""Timeouts occurred with the request"""

    data: TimeoutErrorTData

    def __init__(self, data: TimeoutErrorTData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, TimeoutErrorTData)
