overlay: 1.0.0
info:
  title: Speakeasy Suggestions - weather.gov API
  version: 0.0.1
actions:
  - target: $["paths"]["/stations"]["get"]
    update:
      x-speakeasy-name-override: list
    x-speakeasy-metadata:
      after: sdk.observationstations.list()
      before: sdk.observationstations.list_observation_stations()
      type: method-name
  - target: $["paths"]["/products/types/{typeId}"]["get"]
    update:
      x-speakeasy-name-override: listByType
    x-speakeasy-metadata:
      after: sdk.products.listByType()
      before: sdk.products.list_products_by_type()
      type: method-name
  - target: $["paths"]["/offices/{officeId}"]["get"]
    update:
      x-speakeasy-name-override: getMetadata
    x-speakeasy-metadata:
      after: sdk.offices.getMetadata()
      before: sdk.offices.get_office_metadata()
      type: method-name
  - target: $["paths"]["/gridpoints/{wfo}/{point}/stations"]["get"]
    update:
      x-speakeasy-name-override: listObservationStations
    x-speakeasy-metadata:
      after: sdk.gridpoints.listObservationStations()
      before: sdk.gridpoints.list_observation_stations_by_gridpoint()
      type: method-name
  - target: $["paths"]["/aviation/sigmets"]["get"]
    update:
      x-speakeasy-name-override: getSigmets
    x-speakeasy-metadata:
      after: sdk.aviation.getSigmets()
      before: sdk.aviation.list_sigmets()
      type: method-name
  - target: $["paths"]["/stations/{stationId}/observations/{time}"]["get"]
    update:
      x-speakeasy-name-override: getByStation
    x-speakeasy-metadata:
      after: sdk.observationstations.getByStation()
      before: sdk.observationstations.get_observation_by_station()
      type: method-name
  - target: $["paths"]["/offices/{officeId}/headlines/{headlineId}"]["get"]
    update:
      x-speakeasy-name-override: getHeadline
    x-speakeasy-metadata:
      after: sdk.offices.getHeadline()
      before: sdk.offices.get_office_headline()
      type: method-name
  - target: $["paths"]["/radar/servers/{id}"]["get"]
    update:
      x-speakeasy-name-override: getServerMetadata
    x-speakeasy-metadata:
      after: sdk.radar.getServerMetadata()
      before: sdk.radar.get_radar_server_metadata()
      type: method-name
  - target: $["paths"]["/alerts/{id}"]["get"]
    update:
      x-speakeasy-name-override: get
    x-speakeasy-metadata:
      after: sdk.alerts.get()
      before: sdk.alerts.get_alert()
      type: method-name
  - target: $["paths"]["/aviation/cwsus/{cwsuId}"]["get"]
    update:
      x-speakeasy-name-override: getCwsu
    x-speakeasy-metadata:
      after: sdk.aviation.getCwsu()
      before: sdk.aviation.get_CWSU()
      type: method-name
  - target: $["paths"]["/stations/{stationId}/tafs"]["get"]
    update:
      x-speakeasy-name-override: listTafs
    x-speakeasy-metadata:
      after: sdk.observationstations.listTAFs()
      before: sdk.observationstations.list_tafs()
      type: method-name
  - target: $["paths"]["/stations/{stationId}/tafs/{date}/{time}"]["get"]
    update:
      x-speakeasy-name-override: getTAF
    x-speakeasy-metadata:
      after: sdk.observationstations.getTAF()
      before: sdk.observationstations.get_taf()
      type: method-name
  - target: $["paths"]["/products/{productId}"]["get"]
    update:
      x-speakeasy-name-override: getById
    x-speakeasy-metadata:
      after: sdk.products.getById()
      before: sdk.products.get_product_by_id()
      type: method-name
  - target: $["paths"]["/products/types/{typeId}/locations/{locationId}"]["get"]
    update:
      x-speakeasy-name-override: listByTypeAndLocation
    x-speakeasy-metadata:
      after: sdk.products.listByTypeAndLocation()
      before: sdk.products.list_products_by_type_and_location()
      type: method-name
  - target: $["paths"]["/products/locations"]["get"]
    update:
      x-speakeasy-name-override: listLocations
    x-speakeasy-metadata:
      after: sdk.products.listLocations()
      before: sdk.products.list_product_locations()
      type: method-name
  - target: $["paths"]["/aviation/cwsus/{cwsuId}/cwas"]["get"]
    update:
      x-speakeasy-name-override: listCwas
    x-speakeasy-metadata:
      after: sdk.aviation.listCWAs()
      before: sdk.aviation.list_cwas()
      type: method-name
  - target: $["paths"]["/radar/servers"]["get"]
    update:
      x-speakeasy-name-override: listServers
    x-speakeasy-metadata:
      after: sdk.radar.listServers()
      before: sdk.radar.list_radar_servers()
      type: method-name
  - target: $["paths"]["/products/types/{typeId}/locations"]["get"]
    update:
      x-speakeasy-name-override: getLocationsByType
    x-speakeasy-metadata:
      after: sdk.products.getLocationsByType()
      before: sdk.products.list_locations_by_product_type()
      type: method-name
  - target: $["paths"]["/gridpoints/{wfo}/{point}/forecast/hourly"]["get"]
    update:
      x-speakeasy-name-override: getHourlyForecast
    x-speakeasy-metadata:
      after: sdk.gridpoints.getHourlyForecast()
      before: sdk.gridpoints.get_gridpoint_hourly_forecast()
      type: method-name
  - target: $["paths"]["/zones/forecast/{zoneId}/observations"]["get"]
    update:
      x-speakeasy-name-override: listObservations
    x-speakeasy-metadata:
      after: sdk.zones.listObservations()
      before: sdk.zones.list_observations_by_zone()
      type: method-name
  - target: $["paths"]["/radar/stations/{stationId}/alarms"]["get"]
    update:
      x-speakeasy-name-override: getStationAlarmsMetadata
    x-speakeasy-metadata:
      after: sdk.radar.getStationAlarmsMetadata()
      before: sdk.radar.get_radar_station_alarms_metadata()
      type: method-name
  - target: $["paths"]["/stations/{stationId}"]["get"]
    update:
      x-speakeasy-name-override: getMetadata
    x-speakeasy-metadata:
      after: sdk.observationstations.getMetadata()
      before: sdk.observationstations.get_observation_station_metadata()
      type: method-name
  - target: $["paths"]["/zones"]["get"]
    update:
      x-speakeasy-name-override: list
    x-speakeasy-metadata:
      after: sdk.zones.list()
      before: sdk.zones.list_zones()
      type: method-name
  - target: $["paths"]["/alerts/types"]["get"]
    update:
      x-speakeasy-name-override: listTypes
    x-speakeasy-metadata:
      after: sdk.alerts.listTypes()
      before: sdk.alerts.list_alert_types()
      type: method-name
  - target: $["paths"]["/aviation/sigmets/{atsu}/{date}/{time}"]["get"]
    update:
      x-speakeasy-name-override: getSigmet
    x-speakeasy-metadata:
      after: sdk.aviation.getSigmet()
      before: sdk.aviation.get_sigmet()
      type: method-name
  - target: $["paths"]["/alerts/active/zone/{zoneId}"]["get"]
    update:
      x-speakeasy-name-override: listActiveByZone
    x-speakeasy-metadata:
      after: sdk.alerts.listActiveByZone()
      before: sdk.alerts.list_active_alerts_by_zone()
      type: method-name
  - target: $["paths"]["/zones/{type}/{zoneId}/forecast"]["get"]
    update:
      x-speakeasy-name-override: getForecast
    x-speakeasy-metadata:
      after: sdk.zones.getForecast()
      before: sdk.zones.get_zone_forecast()
      type: method-name
  - target: $["paths"]["/radar/stations/{stationId}"]["get"]
    update:
      x-speakeasy-name-override: getStationMetadata
    x-speakeasy-metadata:
      after: sdk.radar.getStationMetadata()
      before: sdk.radar.get_radar_station_metadata()
      type: method-name
  - target: $["paths"]["/zones/{type}/{zoneId}"]["get"]
    update:
      x-speakeasy-name-override: getMetadata
    x-speakeasy-metadata:
      after: sdk.zones.getMetadata()
      before: sdk.zones.get_zone_metadata()
      type: method-name
  - target: $["paths"]["/alerts/active/area/{area}"]["get"]
    update:
      x-speakeasy-name-override: listActiveByArea
    x-speakeasy-metadata:
      after: sdk.alerts.listActiveByArea()
      before: sdk.alerts.list_active_alerts_by_area()
      type: method-name
  - target: $["paths"]["/products/locations/{locationId}/types"]["get"]
    update:
      x-speakeasy-name-override: listTypesByLocation
    x-speakeasy-metadata:
      after: sdk.products.listTypesByLocation()
      before: sdk.products.list_product_types_by_location()
      type: method-name
  - target: $["paths"]["/points/{point}"]["get"]
    update:
      x-speakeasy-name-override: getMetadata
    x-speakeasy-metadata:
      after: sdk.points.getMetadata()
      before: sdk.points.get_point_metadata()
      type: method-name
  - target: $["paths"]["/alerts/active/region/{region}"]["get"]
    update:
      x-speakeasy-name-override: listActiveByRegion
    x-speakeasy-metadata:
      after: sdk.alerts.listActiveByRegion()
      before: sdk.alerts.list_active_alerts_by_region()
      type: method-name
  - target: $["paths"]["/gridpoints/{wfo}/{point}"]["get"]
    update:
      x-speakeasy-name-override: getRawForecast
    x-speakeasy-metadata:
      after: sdk.gridpoints.getRawForecast()
      before: sdk.gridpoints.get_gridpoint_raw_forecast()
      type: method-name
  - target: $["paths"]["/zones/{type}"]["get"]
    update:
      x-speakeasy-name-override: listByType
    x-speakeasy-metadata:
      after: sdk.zones.listByType()
      before: sdk.zones.list_zones_by_type()
      type: method-name
  - target: $["paths"]["/alerts/active/count"]["get"]
    update:
      x-speakeasy-name-override: listActiveCount
    x-speakeasy-metadata:
      after: sdk.alerts.listActiveCount()
      before: sdk.alerts.list_active_alert_counts()
      type: method-name
  - target: $["paths"]["/radar/profilers/{stationId}"]["get"]
    update:
      x-speakeasy-name-override: getWindProfilerMetadata
    x-speakeasy-metadata:
      after: sdk.radar.getWindProfilerMetadata()
      before: sdk.radar.get_radar_wind_profiler_metadata()
      type: method-name
  - target: $["paths"]["/offices/{officeId}/headlines"]["get"]
    update:
      x-speakeasy-name-override: listHeadlines
    x-speakeasy-metadata:
      after: sdk.offices.listHeadlines()
      before: sdk.offices.list_office_headlines()
      type: method-name
  - target: $["paths"]["/gridpoints/{wfo}/{point}/forecast"]["get"]
    update:
      x-speakeasy-name-override: getForecast
    x-speakeasy-metadata:
      after: sdk.gridpoints.getForecast()
      before: sdk.gridpoints.get_gridpoint_forecast()
      type: method-name
  - target: $["paths"]["/radar/queues/{host}"]["get"]
    update:
      x-speakeasy-name-override: getQueueMetadata
    x-speakeasy-metadata:
      after: sdk.radar.getQueueMetadata()
      before: sdk.radar.get_radar_queue_metadata()
      type: method-name
  - target: $["paths"]["/stations/{stationId}/observations"]["get"]
    update:
      x-speakeasy-group: observations
      x-speakeasy-name-override: listByStation
    x-speakeasy-metadata:
      after: sdk.observations.listByStation()
      before: sdk.observationstations.list_observations_by_station()
      type: method-name
  - target: $["paths"]["/radar/stations"]["get"]
    update:
      x-speakeasy-name-override: listStations
    x-speakeasy-metadata:
      after: sdk.radar.listStations()
      before: sdk.radar.list_radar_stations()
      type: method-name
  - target: $["paths"]["/products"]["get"]
    update:
      x-speakeasy-name-override: list
    x-speakeasy-metadata:
      after: sdk.products.list()
      before: sdk.products.list_products()
      type: method-name
  - target: $["paths"]["/stations/{stationId}/observations/latest"]["get"]
    update:
      x-speakeasy-name-override: getLatestObservation
    x-speakeasy-metadata:
      after: sdk.observationstations.getLatestObservation()
      before: sdk.observationstations.get_latest_observation_by_station()
      type: method-name
  - target: $["paths"]["/glossary"]["get"]
    update:
      x-speakeasy-name-override: listTerms
    x-speakeasy-metadata:
      after: sdk.glossary.listTerms()
      before: sdk.glossary.list_terms()
      type: method-name
  - target: $["paths"]["/products/types"]["get"]
    update:
      x-speakeasy-name-override: listTypes
    x-speakeasy-metadata:
      after: sdk.products.listTypes()
      before: sdk.products.list_product_types()
      type: method-name
  - target: $["paths"]["/aviation/sigmets/{atsu}"]["get"]
    update:
      x-speakeasy-name-override: listSigmets
    x-speakeasy-metadata:
      after: sdk.aviation.listSigmets()
      before: sdk.aviation.list_sigmets_by_atsu()
      type: method-name
  - target: $["paths"]["/aviation/sigmets/{atsu}/{date}"]["get"]
    update:
      x-speakeasy-name-override: listSigmetsByAtsuAndDate
    x-speakeasy-metadata:
      after: sdk.aviation.listSigmetsByAtsuAndDate()
      before: sdk.aviation.list_sigmets_by_atsu_and_date()
      type: method-name
  - target: $["paths"]["/aviation/cwsus/{cwsuId}/cwas/{date}/{sequence}"]["get"]
    update:
      x-speakeasy-name-override: listCwasByDateAndSequence
    x-speakeasy-metadata:
      after: sdk.aviation.listCwasByDateAndSequence()
      before: sdk.aviation.list_cwas_by_date_and_sequence()
      type: method-name
  - target: $["paths"]["/alerts/active"]["get"]
    update:
      x-speakeasy-name-override: listActive
    x-speakeasy-metadata:
      after: sdk.alerts.listActive()
      before: sdk.alerts.list_active_alerts()
      type: method-name
  - target: $["paths"]["/zones/forecast/{zoneId}/stations"]["get"]
    update:
      x-speakeasy-name-override: listStationsByZone
    x-speakeasy-metadata:
      after: sdk.zones.listStationsByZone()
      before: sdk.zones.list_observation_stations_by_zone()
      type: method-name
