"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.models.components import (
    centerweatherserviceunitjsonld as components_centerweatherserviceunitjsonld,
    nwsofficeid as components_nwsofficeid,
)
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetOfficeInfoGlobalsTypedDict(TypedDict):
    office_id: NotRequired[components_nwsofficeid.NWSOfficeID]
    r"""NWS office ID"""


class GetOfficeInfoGlobals(BaseModel):
    office_id: Annotated[
        Optional[components_nwsofficeid.NWSOfficeID],
        pydantic.Field(alias="officeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""NWS office ID"""


class GetOfficeInfoRequestTypedDict(TypedDict):
    office_id: NotRequired[components_nwsofficeid.NWSOfficeID]
    r"""NWS office ID"""


class GetOfficeInfoRequest(BaseModel):
    office_id: Annotated[
        Optional[components_nwsofficeid.NWSOfficeID],
        pydantic.Field(alias="officeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""NWS office ID"""


class GetOfficeInfoResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: components_centerweatherserviceunitjsonld.CenterWeatherServiceUnitJSONLdTypedDict


class GetOfficeInfoResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_centerweatherserviceunitjsonld.CenterWeatherServiceUnitJSONLd
