"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRadarStationQueueRequestTypedDict(TypedDict):
    host: str
    r"""LDM host"""
    limit: NotRequired[int]
    r"""Limit"""
    arrived: NotRequired[str]
    r"""Range for arrival time"""
    created: NotRequired[str]
    r"""Range for creation time"""
    published: NotRequired[str]
    r"""Range for publish time"""
    station: NotRequired[str]
    r"""Station identifier"""
    type: NotRequired[str]
    r"""Record type"""
    feed: NotRequired[str]
    r"""Originating product feed"""
    resolution: NotRequired[int]
    r"""Resolution version"""


class GetRadarStationQueueRequest(BaseModel):
    host: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""LDM host"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 500
    r"""Limit"""

    arrived: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Range for arrival time"""

    created: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Range for creation time"""

    published: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Range for publish time"""

    station: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Station identifier"""

    type: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Record type"""

    feed: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Originating product feed"""

    resolution: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Resolution version"""


class GetRadarStationQueueResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: Any


class GetRadarStationQueueResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Any
