"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.models.components import (
    textproductlocationcollection as components_textproductlocationcollection,
)
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class GetLocationsByProductTypeRequestTypedDict(TypedDict):
    type_id: str
    r"""."""


class GetLocationsByProductTypeRequest(BaseModel):
    type_id: Annotated[
        str,
        pydantic.Field(alias="typeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""."""


class GetLocationsByProductTypeResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: (
        components_textproductlocationcollection.TextProductLocationCollectionTypedDict
    )


class GetLocationsByProductTypeResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_textproductlocationcollection.TextProductLocationCollection
