"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.models.components import alertstypes as components_alertstypes
from nws_api_client.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class GetAlertTypesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: components_alertstypes.AlertsTypesTypedDict


class GetAlertTypesResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: components_alertstypes.AlertsTypes
