"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRadarServersRequestTypedDict(TypedDict):
    reporting_host: NotRequired[str]
    r"""Show records from specific reporting host"""


class GetRadarServersRequest(BaseModel):
    reporting_host: Annotated[
        Optional[str],
        pydantic.Field(alias="reportingHost"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Show records from specific reporting host"""


class GetRadarServersResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: Any


class GetRadarServersResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Any
