"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AlertXMLParameterTypedDict(TypedDict):
    value_name: NotRequired[str]
    value: NotRequired[str]


class AlertXMLParameter(BaseModel):
    value_name: Optional[str] = None

    value: Optional[str] = None
