"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertxmlparameter import AlertXMLParameter, AlertXMLParameterTypedDict
from nws_api_client.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AlertAtomEntryAuthorTypedDict(TypedDict):
    name: NotRequired[str]


class AlertAtomEntryAuthor(BaseModel):
    name: Optional[str] = None


class AlertAtomEntryTypedDict(TypedDict):
    r"""An alert entry in an Atom feed"""

    area_desc: NotRequired[str]
    author: NotRequired[AlertAtomEntryAuthorTypedDict]
    category: NotRequired[str]
    certainty: NotRequired[str]
    effective: NotRequired[str]
    event: NotRequired[str]
    expires: NotRequired[str]
    geocode: NotRequired[List[AlertXMLParameterTypedDict]]
    id: NotRequired[str]
    msg_type: NotRequired[str]
    parameter: NotRequired[List[AlertXMLParameterTypedDict]]
    polygon: NotRequired[str]
    published: NotRequired[str]
    sent: NotRequired[str]
    severity: NotRequired[str]
    status: NotRequired[str]
    summary: NotRequired[str]
    updated: NotRequired[str]
    urgency: NotRequired[str]


class AlertAtomEntry(BaseModel):
    r"""An alert entry in an Atom feed"""

    area_desc: Optional[str] = None

    author: Optional[AlertAtomEntryAuthor] = None

    category: Optional[str] = None

    certainty: Optional[str] = None

    effective: Optional[str] = None

    event: Optional[str] = None

    expires: Optional[str] = None

    geocode: Optional[List[AlertXMLParameter]] = None

    id: Optional[str] = None

    msg_type: Optional[str] = None

    parameter: Optional[List[AlertXMLParameter]] = None

    polygon: Optional[str] = None

    published: Optional[str] = None

    sent: Optional[str] = None

    severity: Optional[str] = None

    status: Optional[str] = None

    summary: Optional[str] = None

    updated: Optional[str] = None

    urgency: Optional[str] = None
