"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.types import BaseModel
from typing_extensions import TypedDict


class AlertCapTypedDict(TypedDict):
    pass


class AlertCap(BaseModel):
    pass
