"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertcollectiongeojson import (
    AlertCollectionGeoJSON,
    AlertCollectionGeoJSONTypedDict,
)
from .alertcollectionjsonld import AlertCollectionJSONLd, AlertCollectionJSONLdTypedDict
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from enum import Enum
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class Area(str, Enum):
    r"""State or marine area code"""

    AL = "AL"
    AK = "AK"
    AS = "AS"
    AR = "AR"
    AZ = "AZ"
    CA = "CA"
    CO = "CO"
    CT = "CT"
    DE = "DE"
    DC = "DC"
    FL = "FL"
    GA = "GA"
    GU = "GU"
    HI = "HI"
    ID = "ID"
    IL = "IL"
    IN = "IN"
    IA = "IA"
    KS = "KS"
    KY = "KY"
    LA = "LA"
    ME = "ME"
    MD = "MD"
    MA = "MA"
    MI = "MI"
    MN = "MN"
    MS = "MS"
    MO = "MO"
    MT = "MT"
    NE = "NE"
    NV = "NV"
    NH = "NH"
    NJ = "NJ"
    NM = "NM"
    NY = "NY"
    NC = "NC"
    ND = "ND"
    OH = "OH"
    OK = "OK"
    OR = "OR"
    PA = "PA"
    PR = "PR"
    RI = "RI"
    SC = "SC"
    SD = "SD"
    TN = "TN"
    TX = "TX"
    UT = "UT"
    VT = "VT"
    VI = "VI"
    VA = "VA"
    WA = "WA"
    WV = "WV"
    WI = "WI"
    WY = "WY"
    MP = "MP"
    PW = "PW"
    FM = "FM"
    MH = "MH"
    AM = "AM"
    AN = "AN"
    GM = "GM"
    LC = "LC"
    LE = "LE"
    LH = "LH"
    LM = "LM"
    LO = "LO"
    LS = "LS"
    PH = "PH"
    PK = "PK"
    PM = "PM"
    PS = "PS"
    PZ = "PZ"
    SL = "SL"


class AlertsActiveAreaRequestTypedDict(TypedDict):
    area: Area
    r"""State or marine area code"""


class AlertsActiveAreaRequest(BaseModel):
    area: Annotated[
        Area, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""State or marine area code"""


AlertsActiveAreaResponseResultTypedDict = TypeAliasType(
    "AlertsActiveAreaResponseResultTypedDict",
    Union[
        AlertCollectionJSONLdTypedDict,
        AlertCollectionGeoJSONTypedDict,
        ProblemDetailTypedDict,
        bytes,
    ],
)


AlertsActiveAreaResponseResult = TypeAliasType(
    "AlertsActiveAreaResponseResult",
    Union[AlertCollectionJSONLd, AlertCollectionGeoJSON, ProblemDetail, bytes],
)


class AlertsActiveAreaResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: AlertsActiveAreaResponseResultTypedDict


class AlertsActiveAreaResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: AlertsActiveAreaResponseResult
