"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AreaCode(str, Enum):
    r"""State, territory, and marine area codes.
    Marine area code as defined in NWS Directive 10-302:
    * AM: Western North Atlantic Ocean and along U.S. East Coast south of Currituck Beach Light NC following the coastline into Gulf of Mexico to Ocean Reef FL including the Caribbean
    * AN: Western North Atlantic Ocean and along U.S. East Coast from Canadian border south to Currituck Beach Light NC
    * GM: Gulf of Mexico and along the U.S. Gulf Coast from the Mexican border to Ocean Reef FL
    * LC: Lake St. Clair
    * LE: Lake Erie
    * LH: Lake Huron
    * LM: Lake Michigan
    * LO: Lake Ontario
    * LS: Lake Superior
    * PH: Central Pacific Ocean including Hawaiian waters
    * PK: North Pacific Ocean near Alaska and along Alaska coastline including the Bering Sea and the Gulf of Alaska
    * PM: Western Pacific Ocean including Mariana Island waters
    * PS: South Central Pacific Ocean including American Samoa waters
    * PZ: Eastern North Pacific Ocean and along U.S. West Coast from Canadian border to Mexican border
    * SL: St. Lawrence River above St. Regis

    """

    AL = "AL"
    AK = "AK"
    AS = "AS"
    AR = "AR"
    AZ = "AZ"
    CA = "CA"
    CO = "CO"
    CT = "CT"
    DE = "DE"
    DC = "DC"
    FL = "FL"
    GA = "GA"
    GU = "GU"
    HI = "HI"
    ID = "ID"
    IL = "IL"
    IN = "IN"
    IA = "IA"
    KS = "KS"
    KY = "KY"
    LA = "LA"
    ME = "ME"
    MD = "MD"
    MA = "MA"
    MI = "MI"
    MN = "MN"
    MS = "MS"
    MO = "MO"
    MT = "MT"
    NE = "NE"
    NV = "NV"
    NH = "NH"
    NJ = "NJ"
    NM = "NM"
    NY = "NY"
    NC = "NC"
    ND = "ND"
    OH = "OH"
    OK = "OK"
    OR = "OR"
    PA = "PA"
    PR = "PR"
    RI = "RI"
    SC = "SC"
    SD = "SD"
    TN = "TN"
    TX = "TX"
    UT = "UT"
    VT = "VT"
    VI = "VI"
    VA = "VA"
    WA = "WA"
    WV = "WV"
    WI = "WI"
    WY = "WY"
    MP = "MP"
    PW = "PW"
    FM = "FM"
    MH = "MH"
    AM = "AM"
    AN = "AN"
    GM = "GM"
    LC = "LC"
    LE = "LE"
    LH = "LH"
    LM = "LM"
    LO = "LO"
    LS = "LS"
    PH = "PH"
    PK = "PK"
    PM = "PM"
    PS = "PS"
    PZ = "PZ"
    SL = "SL"
