"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .centerweatherserviceunitjsonld import (
    CenterWeatherServiceUnitJSONLd,
    CenterWeatherServiceUnitJSONLdTypedDict,
)
from .nwscenterweatherserviceunitid import NWSCenterWeatherServiceUnitID
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class GetCwsuRequestTypedDict(TypedDict):
    cwsu_id: NWSCenterWeatherServiceUnitID
    r"""NWS CWSU ID"""


class GetCwsuRequest(BaseModel):
    cwsu_id: Annotated[
        NWSCenterWeatherServiceUnitID,
        pydantic.Field(alias="cwsuId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""NWS CWSU ID"""


GetCwsuResponseResultTypedDict = TypeAliasType(
    "GetCwsuResponseResultTypedDict",
    Union[ProblemDetailTypedDict, CenterWeatherServiceUnitJSONLdTypedDict],
)


GetCwsuResponseResult = TypeAliasType(
    "GetCwsuResponseResult", Union[ProblemDetail, CenterWeatherServiceUnitJSONLd]
)


class GetCwsuResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: GetCwsuResponseResultTypedDict


class GetCwsuResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetCwsuResponseResult
