"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .textproductlocationcollection import (
    TextProductLocationCollection,
    TextProductLocationCollectionTypedDict,
)
from nws_api_client.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypeAliasType, TypedDict


ListProductLocationsResponseResultTypedDict = TypeAliasType(
    "ListProductLocationsResponseResultTypedDict",
    Union[TextProductLocationCollectionTypedDict, ProblemDetailTypedDict],
)


ListProductLocationsResponseResult = TypeAliasType(
    "ListProductLocationsResponseResult",
    Union[TextProductLocationCollection, ProblemDetail],
)


class ListProductLocationsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListProductLocationsResponseResultTypedDict


class ListProductLocationsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ListProductLocationsResponseResult
