"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .textproductcollection import TextProductCollection, TextProductCollectionTypedDict
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class ListProductsByTypeAndLocationRequestTypedDict(TypedDict):
    type_id: str
    r"""."""
    location_id: str
    r"""."""


class ListProductsByTypeAndLocationRequest(BaseModel):
    type_id: Annotated[
        str,
        pydantic.Field(alias="typeId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""."""

    location_id: Annotated[
        str,
        pydantic.Field(alias="locationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""."""


ListProductsByTypeAndLocationResponseResultTypedDict = TypeAliasType(
    "ListProductsByTypeAndLocationResponseResultTypedDict",
    Union[TextProductCollectionTypedDict, ProblemDetailTypedDict],
)


ListProductsByTypeAndLocationResponseResult = TypeAliasType(
    "ListProductsByTypeAndLocationResponseResult",
    Union[TextProductCollection, ProblemDetail],
)


class ListProductsByTypeAndLocationResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListProductsByTypeAndLocationResponseResultTypedDict


class ListProductsByTypeAndLocationResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ListProductsByTypeAndLocationResponseResult
