"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .textproducttypecollection import (
    TextProductTypeCollection,
    TextProductTypeCollectionTypedDict,
)
from nws_api_client.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypeAliasType, TypedDict


ListProductTypesResponseResultTypedDict = TypeAliasType(
    "ListProductTypesResponseResultTypedDict",
    Union[TextProductTypeCollectionTypedDict, ProblemDetailTypedDict],
)


ListProductTypesResponseResult = TypeAliasType(
    "ListProductTypesResponseResult", Union[TextProductTypeCollection, ProblemDetail]
)


class ListProductTypesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListProductTypesResponseResultTypedDict


class ListProductTypesResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ListProductTypesResponseResult
