"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .sigmetcollectiongeojson import (
    SigmetCollectionGeoJSON,
    SigmetCollectionGeoJSONTypedDict,
)
from nws_api_client.types import BaseModel
from nws_api_client.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class ListSigmetsByAtsuRequestTypedDict(TypedDict):
    atsu: str
    r"""ATSU identifier"""


class ListSigmetsByAtsuRequest(BaseModel):
    atsu: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ATSU identifier"""


ListSigmetsByAtsuResponseResultTypedDict = TypeAliasType(
    "ListSigmetsByAtsuResponseResultTypedDict",
    Union[SigmetCollectionGeoJSONTypedDict, ProblemDetailTypedDict],
)


ListSigmetsByAtsuResponseResult = TypeAliasType(
    "ListSigmetsByAtsuResponseResult", Union[SigmetCollectionGeoJSON, ProblemDetail]
)


class ListSigmetsByAtsuResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ListSigmetsByAtsuResponseResultTypedDict


class ListSigmetsByAtsuResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ListSigmetsByAtsuResponseResult
