"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .textproductlocationcollection import (
    TextProductLocationCollection,
    TextProductLocationCollectionTypedDict,
)
from nws_api_client.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypeAliasType, TypedDict


ProductLocationsResponseResultTypedDict = TypeAliasType(
    "ProductLocationsResponseResultTypedDict",
    Union[TextProductLocationCollectionTypedDict, ProblemDetailTypedDict],
)


ProductLocationsResponseResult = TypeAliasType(
    "ProductLocationsResponseResult",
    Union[TextProductLocationCollection, ProblemDetail],
)


class ProductLocationsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ProductLocationsResponseResultTypedDict


class ProductLocationsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ProductLocationsResponseResult
