"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .textproducttypecollection import (
    TextProductTypeCollection,
    TextProductTypeCollectionTypedDict,
)
from nws_api_client.types import BaseModel
from typing import Dict, List, Union
from typing_extensions import TypeAliasType, TypedDict


ProductTypesResponseResultTypedDict = TypeAliasType(
    "ProductTypesResponseResultTypedDict",
    Union[TextProductTypeCollectionTypedDict, ProblemDetailTypedDict],
)


ProductTypesResponseResult = TypeAliasType(
    "ProductTypesResponseResult", Union[TextProductTypeCollection, ProblemDetail]
)


class ProductTypesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: ProductTypesResponseResultTypedDict


class ProductTypesResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ProductTypesResponseResult
