"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alert import Alert, AlertTypedDict
from .jsonldcontext_union import JSONLdContextUnion, JSONLdContextUnionTypedDict
from .paginationinfo import PaginationInfo, PaginationInfoTypedDict
from datetime import datetime
from nws_client.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AlertCollectionJSONLdTypedDict(TypedDict):
    title: NotRequired[str]
    r"""A title describing the alert collection"""
    updated: NotRequired[datetime]
    r"""The last time a change occurred to this collection"""
    pagination: NotRequired[PaginationInfoTypedDict]
    r"""Links for retrieving more data from paged data sets"""
    at_context: NotRequired[JSONLdContextUnionTypedDict]
    at_graph: NotRequired[List[AlertTypedDict]]


class AlertCollectionJSONLd(BaseModel):
    title: Optional[str] = None
    r"""A title describing the alert collection"""

    updated: Optional[datetime] = None
    r"""The last time a change occurred to this collection"""

    pagination: Optional[PaginationInfo] = None
    r"""Links for retrieving more data from paged data sets"""

    at_context: Annotated[
        Optional[JSONLdContextUnion], pydantic.Field(alias="@context")
    ] = None

    at_graph: Annotated[Optional[List[Alert]], pydantic.Field(alias="@graph")] = None
