"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class GridpointForecastUnits(str, Enum):
    r"""Denotes the units used in the textual portions of the forecast."""

    US = "us"
    SI = "si"
