"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .sizes import Sizes
import httpx
from nws_client.types import BaseModel
from nws_client.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


IconsDualConditionSizeTypedDict = TypeAliasType(
    "IconsDualConditionSizeTypedDict", Union[Sizes, int]
)
r"""Font size"""


IconsDualConditionSize = TypeAliasType("IconsDualConditionSize", Union[Sizes, int])
r"""Font size"""


class IconsDualConditionRequestTypedDict(TypedDict):
    set: str
    r"""."""
    time_of_day: str
    r"""."""
    first: str
    r"""."""
    second: str
    r"""."""
    size: NotRequired[IconsDualConditionSizeTypedDict]
    r"""Font size"""
    fontsize: NotRequired[int]
    r"""Font size"""


class IconsDualConditionRequest(BaseModel):
    set: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""."""

    time_of_day: Annotated[
        str,
        pydantic.Field(alias="timeOfDay"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""."""

    first: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""."""

    second: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""."""

    size: Annotated[
        Optional[IconsDualConditionSize],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Font size"""

    fontsize: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Font size"""


IconsDualConditionResponseResultTypedDict = TypeAliasType(
    "IconsDualConditionResponseResultTypedDict",
    Union[ProblemDetailTypedDict, httpx.Response],
)


IconsDualConditionResponseResult = TypeAliasType(
    "IconsDualConditionResponseResult", Union[ProblemDetail, httpx.Response]
)


class IconsDualConditionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: IconsDualConditionResponseResultTypedDict


class IconsDualConditionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: IconsDualConditionResponseResult
