"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from nws_client.types import BaseModel
from nws_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class RadarStationAlarmsRequestTypedDict(TypedDict):
    station_id: str
    r"""Radar station ID"""


class RadarStationAlarmsRequest(BaseModel):
    station_id: Annotated[
        str,
        pydantic.Field(alias="stationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Radar station ID"""


RadarStationAlarmsResponseResultTypedDict = TypeAliasType(
    "RadarStationAlarmsResponseResultTypedDict", Union[ProblemDetailTypedDict, Any]
)


RadarStationAlarmsResponseResult = TypeAliasType(
    "RadarStationAlarmsResponseResult", Union[ProblemDetail, Any]
)


class RadarStationAlarmsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: RadarStationAlarmsResponseResultTypedDict


class RadarStationAlarmsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: RadarStationAlarmsResponseResult
