"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .quantitativevalue import QuantitativeValue, QuantitativeValueTypedDict
from nws_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RelativeLocationTypedDict(TypedDict):
    city: NotRequired[str]
    state: NotRequired[str]
    distance: NotRequired[QuantitativeValueTypedDict]
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue

    """
    bearing: NotRequired[QuantitativeValueTypedDict]
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue

    """


class RelativeLocation(BaseModel):
    city: Optional[str] = None

    state: Optional[str] = None

    distance: Optional[QuantitativeValue] = None
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue

    """

    bearing: Optional[QuantitativeValue] = None
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue

    """
