"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .sigmetcollectiongeojson import (
    SigmetCollectionGeoJSON,
    SigmetCollectionGeoJSONTypedDict,
)
from datetime import date, datetime
from nws_client.types import BaseModel
from nws_client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SigmetQueryRequestTypedDict(TypedDict):
    start: NotRequired[datetime]
    r"""Start time"""
    end: NotRequired[datetime]
    r"""End time"""
    date_: NotRequired[date]
    r"""Date (YYYY-MM-DD format)"""
    atsu: NotRequired[str]
    r"""ATSU identifier"""
    sequence: NotRequired[str]
    r"""SIGMET sequence number"""


class SigmetQueryRequest(BaseModel):
    start: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Start time"""

    end: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""End time"""

    date_: Annotated[
        Optional[date],
        pydantic.Field(alias="date"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Date (YYYY-MM-DD format)"""

    atsu: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""ATSU identifier"""

    sequence: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""SIGMET sequence number"""


SigmetQueryResponseResultTypedDict = TypeAliasType(
    "SigmetQueryResponseResultTypedDict",
    Union[SigmetCollectionGeoJSONTypedDict, ProblemDetailTypedDict],
)


SigmetQueryResponseResult = TypeAliasType(
    "SigmetQueryResponseResult", Union[SigmetCollectionGeoJSON, ProblemDetail]
)


class SigmetQueryResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: SigmetQueryResponseResultTypedDict


class SigmetQueryResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: SigmetQueryResponseResult
