"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetail import ProblemDetail, ProblemDetailTypedDict
from .sigmetcollectiongeojson import (
    SigmetCollectionGeoJSON,
    SigmetCollectionGeoJSONTypedDict,
)
from datetime import date
from nws_client.types import BaseModel
from nws_client.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class SigmetsByATSUByDateRequestTypedDict(TypedDict):
    atsu: str
    r"""ATSU identifier"""
    date_: date
    r"""Date (YYYY-MM-DD format)"""


class SigmetsByATSUByDateRequest(BaseModel):
    atsu: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ATSU identifier"""

    date_: Annotated[
        date,
        pydantic.Field(alias="date"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Date (YYYY-MM-DD format)"""


SigmetsByATSUByDateResponseResultTypedDict = TypeAliasType(
    "SigmetsByATSUByDateResponseResultTypedDict",
    Union[SigmetCollectionGeoJSONTypedDict, ProblemDetailTypedDict],
)


SigmetsByATSUByDateResponseResult = TypeAliasType(
    "SigmetsByATSUByDateResponseResult", Union[SigmetCollectionGeoJSON, ProblemDetail]
)


class SigmetsByATSUByDateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: SigmetsByATSUByDateResponseResultTypedDict


class SigmetsByATSUByDateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: SigmetsByATSUByDateResponseResult
