workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    weather.gov API:
        inputs:
            - location: ./openapi.yaml
        overlays:
            - location: ./openapi_overlay_operationids.yaml
        transformations:
            - removeUnused: true
            - cleanup: true
        output: ./merged_openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/spdustin/weather/weather-gov-api
targets:
    nws-api-client:
        target: python
        source: weather.gov API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: ./code_samples.yaml
            registry:
                location: registry.speakeasyapi.dev/spdustin/weather/weather-gov-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
