"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonldcontext_union import JSONLdContextUnion, JSONLdContextUnionTypedDict
from enum import Enum
from nws_api_client.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AtTypeGovernmentOrganization(str, Enum):
    GOVERNMENT_ORGANIZATION = "GovernmentOrganization"


class AtTypePostalAddress(str, Enum):
    POSTAL_ADDRESS = "PostalAddress"


class AddressTypedDict(TypedDict):
    at_type: NotRequired[AtTypePostalAddress]
    address_locality: NotRequired[str]
    address_region: NotRequired[str]
    postal_code: NotRequired[str]
    street_address: NotRequired[str]


class Address(BaseModel):
    at_type: Annotated[Optional[AtTypePostalAddress], pydantic.Field(alias="@type")] = (
        None
    )

    address_locality: Annotated[
        Optional[str], pydantic.Field(alias="addressLocality")
    ] = None

    address_region: Annotated[Optional[str], pydantic.Field(alias="addressRegion")] = (
        None
    )

    postal_code: Annotated[Optional[str], pydantic.Field(alias="postalCode")] = None

    street_address: Annotated[Optional[str], pydantic.Field(alias="streetAddress")] = (
        None
    )


class CenterWeatherServiceUnitJSONLdTypedDict(TypedDict):
    at_context: NotRequired[JSONLdContextUnionTypedDict]
    at_id: NotRequired[str]
    at_type: NotRequired[AtTypeGovernmentOrganization]
    address: NotRequired[AddressTypedDict]
    approved_observation_stations: NotRequired[List[str]]
    email: NotRequired[str]
    fax_number: NotRequired[str]
    id: NotRequired[str]
    name: NotRequired[str]
    nws_region: NotRequired[str]
    parent_organization: NotRequired[str]
    responsible_counties: NotRequired[List[str]]
    responsible_fire_zones: NotRequired[List[str]]
    responsible_forecast_zones: NotRequired[List[str]]
    same_as: NotRequired[str]
    telephone: NotRequired[str]


class CenterWeatherServiceUnitJSONLd(BaseModel):
    at_context: Annotated[
        Optional[JSONLdContextUnion], pydantic.Field(alias="@context")
    ] = None

    at_id: Annotated[Optional[str], pydantic.Field(alias="@id")] = None

    at_type: Annotated[
        Optional[AtTypeGovernmentOrganization], pydantic.Field(alias="@type")
    ] = None

    address: Optional[Address] = None

    approved_observation_stations: Annotated[
        Optional[List[str]], pydantic.Field(alias="approvedObservationStations")
    ] = None

    email: Optional[str] = None

    fax_number: Annotated[Optional[str], pydantic.Field(alias="faxNumber")] = None

    id: Optional[str] = None

    name: Optional[str] = None

    nws_region: Annotated[Optional[str], pydantic.Field(alias="nwsRegion")] = None

    parent_organization: Annotated[
        Optional[str], pydantic.Field(alias="parentOrganization")
    ] = None

    responsible_counties: Annotated[
        Optional[List[str]], pydantic.Field(alias="responsibleCounties")
    ] = None

    responsible_fire_zones: Annotated[
        Optional[List[str]], pydantic.Field(alias="responsibleFireZones")
    ] = None

    responsible_forecast_zones: Annotated[
        Optional[List[str]], pydantic.Field(alias="responsibleForecastZones")
    ] = None

    same_as: Annotated[Optional[str], pydantic.Field(alias="sameAs")] = None

    telephone: Optional[str] = None
