"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nws_api_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GlossaryTermTypedDict(TypedDict):
    definition: NotRequired[str]
    r"""A definition for the term"""
    term: NotRequired[str]
    r"""The term being defined"""


class GlossaryTerm(BaseModel):
    definition: Optional[str] = None
    r"""A definition for the term"""

    term: Optional[str] = None
    r"""The term being defined"""
