"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .glossaryterm import GlossaryTerm, GlossaryTermTypedDict
from .jsonldcontext_union import JSONLdContextUnion, JSONLdContextUnionTypedDict
from nws_api_client.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GlossaryTypedDict(TypedDict):
    r"""A set of glossary terms"""

    at_context: NotRequired[JSONLdContextUnionTypedDict]
    glossary: NotRequired[List[GlossaryTermTypedDict]]
    r"""A list of glossary terms"""


class Glossary(BaseModel):
    r"""A set of glossary terms"""

    at_context: Annotated[
        Optional[JSONLdContextUnion], pydantic.Field(alias="@context")
    ] = None

    glossary: Optional[List[GlossaryTerm]] = None
    r"""A list of glossary terms"""
