"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .quantitativevalue import QuantitativeValue, QuantitativeValueTypedDict
from nws_api_client.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RelativeLocationTypedDict(TypedDict):
    bearing: NotRequired[QuantitativeValueTypedDict]
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue"""
    city: NotRequired[str]
    distance: NotRequired[QuantitativeValueTypedDict]
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue"""
    state: NotRequired[str]


class RelativeLocation(BaseModel):
    bearing: Optional[QuantitativeValue] = None
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue"""

    city: Optional[str] = None

    distance: Optional[QuantitativeValue] = None
    r"""A structured value representing a measurement and its unit of measure. This object is a slighly modified version of the schema.org definition at https://schema.org/QuantitativeValue"""

    state: Optional[str] = None
