"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "nws-api-client"
__version__: str = "0.13.1"
__openapi_doc_version__: str = "3.1.0"
__gen_version__: str = "2.597.9"
__user_agent__: str = "speakeasy-sdk/python 0.13.1 2.597.9 3.1.0 nws-api-client"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
